version: '3.8'
services:
  app:
    build: .
    container_name: spring-webapp
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      db:
          condition: service_healthy
          # app будет ждать, пока БД не будет готова
      redis:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: pg-brain-compose
    restart: always
    environment:
      # из .env
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init_data.sql:/docker-entrypoint-initdb.d/init_data.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-webapp
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus
    container_name: prometheus-webapp
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # конфиг, где искать приложение
    extra_hosts:
      - "host.docker.internal:host-gateway" # позволяет Docker видеть порт 8081

  grafana:
    image: grafana/grafana
    container_name: grafana-webapp
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin} # пароль для входа в панель
    volumes:
      - .grafana_storage:/var/lib/grafana
      - ./grafana_init/datasources:/etc/grafana/provisioning/datasources
      - ./grafana_init/dashboards:/etc/grafana/provisioning/dashboards
    user: "0"

volumes:
  grafana_storage: